### ISSUE TITLE
[QUESTION] How to use logger.assign with Bull queue processors?

### ISSUE THREAD

**Issue by JVMartin** [iamolegga/nestjs-pino#993] opened 2022-06-16 22:45 UTC
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**
Each of my Bull Job queue processors logs tons of logs, with no way for me to filter by logs from specific Job processors.

I would love to be able to attach more context to the PinoLogger, so that I can filter by job name. Example:
```ts
import { Job } from 'bull';
import { PinoLogger } from 'nestjs-pino';

export abstract class BaseProcessor<JobType> {
  protected constructor(
    protected readonly logger: PinoLogger,
  ) {}

  public abstract doProcess(job: Job<JobType>): Promise<void>;

  /**
   * Gives us a DRY method for logging the job as well as timing how long
   * it takes to complete, and logging that as well.
   */
  public async wrappedDoProcess(job: Job<JobType>): Promise<void> {
    // Assign job name as logger context.
    // Lets us filter logs for specific jobs.
    this.logger.assign({ jobName: job.name });

    await this.doProcess(job);
  }
}
```

^ this does not work, because the package is hard-coded to only let you add properties in http middleware context.

If this worked, then each of my processors that extended this BaseProcessor would have additional context in their logs, e.g.:
```ts
@Processor(Queues.DEFAULT)
export class DebugProcessor extends BaseProcessor<DebugJob> {
  constructor(
    @InjectPinoLogger(DebugProcessor.name)
    logger: PinoLogger,
  ) {
    super(logger);
  }

  @Process({
    name: Jobs.DEBUG,
  })
  public async process(job: Job<DebugJob>): Promise<void> {
    await this.wrappedDoProcess(job);
  }

  public async doProcess(_: Job<DebugJob>): Promise<void> {
    this.logger.info('hello'); // This should have jobName: 'debug' attached to it (Jobs.DEBUG === 'debug')
  }
}
```

**Comment by JVMartin** [comment] 2022-06-16 23:31
I have a (potentially very problematic / ugly) working implementation:
```ts
export abstract class BaseProcessor<JobType> {
  protected constructor(
    protected readonly logger: PinoLogger,
  ) {}

  public abstract doProcess(job: Job<JobType>): Promise<void>;

  /**
   * Gives us a DRY method for logging the job as well as timing how long
   * it takes to complete, and logging that as well.
   */
  public async wrappedDoProcess(job: Job<JobType>): Promise<void> {
    await storage.run(new Store(this.logger.logger), async () => {
      // Assign job name as logger context.
      // Lets us filter logs for specific jobs.
      this.logger.assign({ jobName: job.name });

      await this.doProcess(job);
    });
  }
}
```

**Comment by iamolegga** [comment] 2022-06-17 06:42
duplicate of #803 that is even pinned in issues

**Closed by iamolegga** 2022-06-17 06:42 UTC
Labels: question
