### ISSUE TITLE
[QUESTION] How to disable http info?

### ISSUE THREAD

**Issue by QRbaba** [iamolegga/nestjs-pino#145] opened 2020-01-01 11:48 UTC
In some situation, i would‘t  want to logging http info (header 、req 、ua and so on) how to diable it？

**Comment by iamolegga** [comment] 2020-01-04 05:42
Duplicate of #122 please subscribe to that issue, I'll try to make it possible soon

**Closed by iamolegga** 2020-01-04 05:42 UTC
Labels: question
