### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Hudi89** [iamolegga/nestjs-pino#971] opened 2022-06-01 19:11 UTC
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

I am working with decimal js and I want to log like this:
```
const a = new Decimal(123);
this.logger.debug(a);
```
If I build up a default setting, I get the following output:
```
{"level":20,"time":1654109511243,"pid":1234,"hostname":"abcd","context":"AppService","s":1,"e":2,"d":[123]}
```

I tried to fix this problem with the pino:logMethod, but in the nestjs-pino if the `Logger:call` gets an object, it reasigns from a simple object, so later it cannot be detected by `instanceof`.
https://github.com/iamolegga/nestjs-pino/blob/master/src/Logger.ts#L52

I build up here two possible solution on the `main` and `solution2` branches:
https://github.com/Hudi89/nestjs-pino-minimal-example

Small change in `Logger:call` and using pino `logMethod`:
https://github.com/Hudi89/nestjs-pino-minimal-example/blob/main/src/app.module.ts

Only change in `Logger:call`.
https://github.com/Hudi89/nestjs-pino-minimal-example/blob/solution2/src/app.module.ts

What do you think how I could do it in a nice way without monkey patching?

**Please mention other relevant information such as Node.js version and Operating System.**
```
    "decimal.js": "^10.3.1",
    "nestjs-pino": "^2.6.0",
    "pino-http": "^7.1.0",
```

node v16.15.0

**Comment by iamolegga** [comment] 2022-06-01 20:34
I believe the most common use case is when object is passed as a record for several values, for example `{ foo: 'bar', baz: 'qux' }`. The problem is that you want to pass this object as some self-sufficient value, right? But it's impossible to determine which of these is desired. I think the most easier way is just pass already stringified value or pass an object with a single prop `{ decimal: decimal }`

**Comment by Hudi89** [comment] 2022-06-02 08:23
Yes I want to pass directly a Decimal object to the logger and as I can see the only obstacle is the merging the message with the `objArg`. Can you tell me what is the reason to merge the logging message into the `objArg` instead of using it similarly in every branch of the if statement?
First argument `objArg`, second the message, rest are the extra optional params.

How you do it:
https://github.com/iamolegga/nestjs-pino/blob/master/src/Logger.ts#L52

How I think should we do it:
https://github.com/Hudi89/nestjs-pino-minimal-example/blob/main/src/app.module.ts#L45

What is the reason you are merging message with the `objArg`? Cannot we use the same signature for object as well?

**Comment by iamolegga** [comment] 2022-06-02 10:26
I cannot say now, I need to setup a project and check what output will be there. If this leads to the breaking change in logging result this should be a new major release, which I would like to avoid, because a lot of projects who already use it as is should change a lot of code, which is unwanted.

I'm closing this as I've provided two quick solutions: stringify object before passing to logger or pass it wrapped in object.

If you think this is a bug let's compare this behavior with the underlying [pino-http](https://github.com/pinojs/pino-http), what result will be if pass this decimal object to the logger in raw express + pino-http example.

**Closed by iamolegga** 2022-06-02 10:26 UTC
Labels: question
