### ISSUE TITLE
[QUESTION] flush logs immediately with bufferLogs: true

### ISSUE THREAD

**Issue by ttoomm318** [iamolegga/nestjs-pino#553] opened 2021-09-20 21:00 UTC
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

With nestjs 8 and nestjs-pino 2+, the recommended approach is to inject nestjs-pino Logger in main.ts only, with
`{ bufferLogs: true }`

However, I would like to flush the logs immediately, so that only the initial nest startup logs are buffered.

What I've tried:

1. Call `Logger.flush()` (`Logger` from `@nestjs/common`)
This works as expected, but I would like to avoid calling `Logger.flush()` after every call to log/error/warn.
2. Extend `Logger` from 'nestjs-pino` based on this: https://github.com/iamolegga/nestjs-pino#loggerpinologger-class-extension and append `Logger.flush()` in the overridden log/error/warn functions.
Logger.flush() doesn't seem to do anything – all logs still seem to be buffered
3. Extend `Logger` from `nestjs-pino` based on this: https://github.com/iamolegga/nestjs-pino#loggerpinologger-class-extension and add an option which, when set to true, will trigger a call to `Logger.flush()` in the overridden log/error/warn functions.
I thought approach 2 might not have worked because I was essentially "disabling" `bufferLogs` completely, forcing logs to flush before `Logger` is setup with nest, but the result is the same – all logs seem to be buffered.

Is there a way to flush logs immediately with `bufferLogs: true` without calling `Logger.flush()` after every call to log/error/warn?

Repository to demonstrate the problem:
https://github.com/ttoomm318/nestjs-pino-extend-logger

**Please mention other relevant information such as Node.js version and Operating System.**

Node: v14.17.6
OSX: 11.5.2
nestjs-pino: 2.2.0
nestjs: 8.0.0

**Comment by iamolegga** [comment] 2021-09-21 15:45
@ttoomm318  If I understand your problem correctly, you are not starting http server, but using nest as DI to build some service and call it immediately, right? I think the problem is that when you pass `bufferLogs: true`, buffering stops after http server run, but this should be checked. Tl;dr you have two options:

- try to drop `bufferLogs: true`
- create your custom basic logger to check if this is a bug of Nest, if yes - this should be fixed on Nest side. if this is a bug of the current lib we will change this issue to bug and fix it, but more info should be added on how to fix it properly, or you can create pr on your own if you already know it

**Comment by ttoomm318** [comment] 2021-09-22 04:38
@iamolegga Thank you very much for the quick response! You are correct, I am building a [standalone application](https://docs.nestjs.com/standalone-applications) with Nest.

I figured out the problem thanks to your comment:

> buffering stops after http server run

With this in mind, I traced through the code path from nestjs-pino to Nest packages and found:

1. With `bufferLogs: true`, a static flag in Nest Logger from `@nestjs/common` package is set to true. Whenever any of the 5 methods (log, error, warn, debug, verbose) are called, if the flag is true, **the entire function reference and the arguments of this particular call** are pushed as an object to Logger's static buffer (array) (see [here](https://github.com/nestjs/nest/blob/664f531d2a1b34217ea5e786539f7ee329acffd5/packages/common/services/logger.service.ts#L65)).

2. A call to `Logger.flush()` sets the static flag to false, **essentially disabling log buffering**, and then **make each function call** stored in the buffer along with stored arguments.

3. The `autoFlushLogs` option, which defaults to true, is only used when using `NestFactory#create()` or `NestFactory. createMicroservice()`. If `autoFlushLogs` is true, a call to `Logger.flush()` is made after http server starts, thus disabling buffering. (see [here](https://github.com/nestjs/nest/blob/df2dab4fccc5e9a32e2305929e09c7392b3daf78/packages/core/nest-application.ts#L282))

Because I am creating a standalone application, flush is not automatically called by Nest. Calling flush in an extended Logger (whether implementing LoggerService directly or extending nestjs-pino Logger) doesn't work either because **the whole function** is buffered, and so flush will never be called.

I solved this by simply called flush right after I replace Nest default Logger with nestjs-pino Logger in main.ts:

```typescript
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { Logger } from 'nestjs-pino';
import { Logger as BaseLogger } from '@nestjs/common';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule, {
    bufferLogs: true,
  });
  const logger = app.get(Logger);
  app.useLogger(logger);
  BaseLogger.flush();
  // other initialization
}
bootstrap();
```

I feel this should be documented as buffering the function call itself is rather unexpected in my opinion (I thought Nest would only buffer the processed log object/string). Should this be documented in Nest or nestjs-pino or both?

**Comment by iamolegga** [comment] 2021-09-22 14:21
I believe this could be in docs of nest because [interface for custom logger implementation](https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts#L9-L40) doesn't have `flush` method, the described above logic is more related to nest core than to one of implementation, because it's common for all of them. But we can add a tiny example of this in the faq section of readme, feel free to open pr, if you would like to. Closing this issue.

**Closed by iamolegga** 2021-09-22 14:21 UTC
Labels: question
