### ISSUE TITLE
[BUG] context don't play well with nestedKey

### ISSUE THREAD

**Issue by flappyBug** [iamolegga/nestjs-pino#674] opened 2021-11-22 15:52 UTC
[ ] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[ ] I've read [the docs of pino](https://getpino.io/#/)

[ ] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**
When config pino with [nestedKey](https://getpino.io/#/docs/api?id=nestedkey-string), the `context` is logged into field configured with `nestedKey`(e.g. `payload`).
```
{...,"payload":{"context":"MyService","actual":"payload"}}
```
**What is the expected behavior?**
We always want to log context in the root of log structure. This can help avoid name conflict.
```
{...,"payload":{"actual":"payload"},"context":"MyService"}
```
**Please provide minimal example repo. Without it this issue will be closed**
```typescript
LoggerModule.forRoot({
  pinoHttp: {
    nestedKey: 'payload',
  },
});
```
**Please mention other relevant information such as Node.js version and Operating System.**

Consider use [`child`](https://getpino.io/#/docs/api?id=child) instead of creating context mixin in origin payload.

**Comment by iamolegga** [comment] 2021-11-23 08:42
This is not a bug at all. If every custom field (not added by `pino` automatically) is moving to the nested key, why should `context` be excluded from that? That's just `nestjs` specific, for `pino` it's pretty the same as any other custom field.

If you want to make an exception to the rule you can open a feature request in `pino`.

Closing

**Closed by iamolegga** 2021-11-23 08:42 UTC
Labels: bug
