### ISSUE TITLE
[QUESTION] Can we use http-pino->customErrorObject ?

### ISSUE THREAD

**Issue by laport-n** [iamolegga/nestjs-pino#1336] opened 2023-02-14 17:37 UTC
- [v] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [v] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [v] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

Hi, we are using nestjs-pino and we want to improve the error logs returned by the library. Searching in pino-http options, it seems that customErrorObject allows to do what I want. But it seems that it is not implemented in the nestjs-pino library? Am I wrong? 
Sorry in advance if I could not find the information by myself. I spent a lot of time searching the documentation and the code, but I don't have many leads yet.

**Please mention other relevant information such as Node.js version and Operating System.**

Some example =>

``` typescript
    LoggerModule.forRoot({
      ...getPinoConfig(config),
      pinoHttp: {
        //Missing method on the pinoHttp: Options
        customErrorObject: (req, res, err, loggableObject) => {
          return {};
        },
        customErrorMessage: (error, res) => {
          const errorResponse: BadRequest = error['response'];
          return `Error:${errorResponse.statusCode}:${errorResponse.error}:${errorResponse.message}`;
        },
        transport: {
          target: 'pino-pretty',
        },
      },
    })
```

**Comment by iamolegga** [comment] 2023-02-14 18:39
> But it seems that it is not implemented in the nestjs-pino library

Should be, it has pino-http as peer deps, so all the types are taken from the installed pino-http version and pino-http options are passed directly to it.

Or you mean it's not working at the runtime?

**Comment by laport-n** [comment] 2023-02-15 09:18
If you take a look on the http-pino readme : 

structured Object Hooks
It is possible to override the default structured object with your own. The hook is provided with the pino-http base object so that you can merge in your own keys.

This is useful in scenarios where you want to augment core pino-http logger object with your own event labels.

If you simply want to change the message which is logged then check out the custom[Received|Error|Success]Message hooks e.g. customReceivedMessage.

I have tried to do something like this :
   
```typescript
    const customLogger = require('http-pino')({
      customErrorObject: (_req, _res, _error, val) => {
        return {
          ...val,
          category: 'ApplicationEvent',
          eventCode: 'REQUEST_FAILED'
        };
      }
    });
   LoggerModule.forRoot({
      ...getPinoConfig(config),
      pinoHttp: {
        //Not working cause pinoHttp have info and the serializer do not work for custom logger
        logger: customLogger,
        customErrorMessage: (error, res) => {
          const errorResponse: BadRequest = error['response'];
          return `Error:${errorResponse.statusCode}:${errorResponse.error}:${errorResponse.message}`;
        },
        transport: {
          target: 'pino-pretty',
        },
      },
    })
```

I found a way to bypass and customize the logs with pino-pretty. But it is currently impossible to use the customErrorObject.. method.
I can't spend more time on it, so for the moment I put my research on standby, but if you have an idea of how to use this method, I'm interested

**Comment by iamolegga** [comment] 2023-02-15 11:22
I'm not sure that you can pass result of `require('pino-http')({...})` to `pinoHttp: { logger }`. If you want to pass custom logger then it should be pino instance, not pino-http middleware. Try just simply define your structured Object Hooks in `pinoHttp: { HERE }`.

Closing, as it seems like the problem with misconfiguration.

Please try to create **minimal** example repo and open a bug issue if you believe that the problem is in current lib

**Closed by iamolegga** 2023-02-15 11:22 UTC
Labels: question
