### ISSUE TITLE
[BUG] TRPC request log issue

### ISSUE THREAD

**Issue by akashdevcc** [iamolegga/nestjs-pino#1926] opened 2024-04-26 21:47 UTC
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)
- [x] This bug is related only to current library or I've tested the same behaviour with the built-in logger and this is not a bug of NestJS.

**What is the current behavior?**
When trpc query is triggered, the service `AppService` writes below logs, without any `req.id` or any other request information:
```sh
INFO (196835): in AppService::greet() method {"context":"AppService"}
```
But when same service `AppService` is triggered via `AppController`, it writes below logs:
```sh
INFO (196835): in AppService::greet() method {"req":{"id":1,"method":"GET","url":"/greet","query":{},"params":{"0":"greet"},"headers":{"host":"localhost:3000","user-agent":"curl/7.81.0","accept":"*/*"},"remoteAddress":"::ffff:127.0.0.1","remotePort":34612},"context":"AppService"}
```
Along with `AppController` logs and the HTTP request log with the `req.id` being logged in every line.

**What is the expected behavior?**
The logs written by `AppService` when triggered through trpc query, should also contain `req.id` and other request information.

**Please provide minimal example repo, not code snippet. Without example repo this issue will be closed.**
Trying to integrate "nestjs-pino" + [trpc](https://github.com/trpc/trpc).
I have integrated both in the minimal example repo (branch: feature/express-trpc-req-log-issue) mentioned below:
https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/tree/feature/express-trpc-req-log-issue

**Steps to reproduce:**
1. Clone the repo.
2. Checkout the branch: `feature/express-trpc-req-log-issue`
3. Do `npm i` and `npm start`
4. In another terminal, trigger command: `curl -X GET "http://localhost:3000/api/trpc/greet"`
5. Logs are written as follows:
```sh
[02:58:02.136] INFO (196835): in AppRouterFactory::greet() trpc path {"context":"AppRouterFactory"}
[02:58:02.137] INFO (196835): in AppService::greet() method {"context":"AppService"}
```
6. Again, trigger command: `curl -X GET "http://localhost:3000/greet"`
7. Logs are written as follows:
```sh
[02:58:39.152] INFO (196835): in AppController::greet() method {"req":{"id":1,"method":"GET","url":"/greet","query":{},"params":{"0":"greet"},"headers":{"host":"localhost:3000","user-agent":"curl/7.81.0","accept":"*/*"},"remoteAddress":"::ffff:127.0.0.1","remotePort":34612},"context":"AppController"}
[02:58:39.152] INFO (196835): in AppService::greet() method {"req":{"id":1,"method":"GET","url":"/greet","query":{},"params":{"0":"greet"},"headers":{"host":"localhost:3000","user-agent":"curl/7.81.0","accept":"*/*"},"remoteAddress":"::ffff:127.0.0.1","remotePort":34612},"context":"AppService"}
[02:58:39.154] INFO (196835): request completed {"req":{"id":1,"method":"GET","url":"/greet","query":{},"params":{"0":"greet"},"headers":{"host":"localhost:3000","user-agent":"curl/7.81.0","accept":"*/*"},"remoteAddress":"::ffff:127.0.0.1","remotePort":34612},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"text/html; charset=utf-8","content-length":"12","etag":"W/\"c-Lve95gjOVATpfV8EL5X4nxwjKHE\""}},"responseTime":3}
```
Expectation is to see the same logs in "Step 5" too as showing in "Step 7", when trpc query is triggered.

I tried to debug the issue and it turns out the `nestjs-pino` `LoggerMiddleware` does not get triggered for "trpc" requests.

I think, this is happening because "trpc" is registered as "NestJS Global Middleware" for different route path `/api/trpc`.
Whereas the `nestjs-pino` `LoggerModule` is registered in `AppModule`, hence the `AppController` logs are getting logged correctly.

**Question:** I am not an expert in NestJS, so this might be a foolish question! But is there a way to enable the `nestjs-pino` logs by applying the `LoggerModule` to the trpc express middleware too?

**Please mention other relevant information such as Node.js version and Operating System.**
Node: v20.10.0
OS: Ubuntu

**Comment by iamolegga** [comment] 2024-04-29 06:40
The first thing I would start from is moving all the logger-related things up as much as possible. For example [here](https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/blob/feature/express-trpc-req-log-issue/src/main.ts#L15-L23) move `app.useLogger(app.get(Logger));` before trpc. Also, I would double check if your trpc router is using nestjs middlewares. Anyway, that's certainly not a bug, just a misconfiguration, so closing.

If this won't help please don't hesitate to submit more details

**Closed by iamolegga** 2024-04-29 06:40 UTC
Labels: bug

**Comment by akashdevcc** [comment] 2024-04-29 10:06
Yes, I am trying to do the same. Moving logger-related things up as much as possible. But moving `app.useLogger(app.get(Logger));` up before trpc, didn't help.

No, trpc fastify plugin does not use nestjs middlewares. So the `nestjs-pino` logger middlewares don't get triggered at all.
And the `req.log` instance doesn't get stored in `AsyncLocalStorage`.

I am trying to see, if I can modify the trpc fastify plugin to run the same code, which `nestjs-pino` does in its `bindLoggerMiddleware` function:

```ts

    let log = req.log;

    if (!useExisting && req.allLogs) {
      log = req.allLogs[req.allLogs.length - 1]!;
    }

    storage.run(new Store(log), next);
```

Is `AsyncLocalStorage` class globally shared for whole application?

**Comment by iamolegga** [comment] 2024-04-29 12:18
I am not familiar with trpc, but I see that you are calling `createExpressMiddleware` yet using fastify adapter, maybe the problem is here?

**Comment by akashdevcc** [comment] 2024-04-29 13:50
No. Both express and fastify has their own branches in this reproduction repo. And the same issue happens with both. 

With express, I think it will be easier to fix this issue, because nestjs middlewares are just express middlewares. So if I modify trpc express middleware a bit it may work.

Issue will be with fastify.

In my project, I will be using fastify due to performance reasons.

I have thought of an approach for fastify, which may require to export the storage from `nestjs-pino` so that I can set it as early as possible in the request lifecycle (may be `onRequest` fastify hook) and will modify `storage.run` call of `nestjs-pino` to only run it if it's not already been set.

Will try to make it work tonight for both express and fastify with their respective approaches!

**Comment by akashdevcc** [comment] 2024-04-30 07:03
@iamolegga The issue has been resolved for express platform.

The solution applied is: As "NestJS Middlewares" are just express middlewares underneath, the "trpc express middleware" is reimplemented as "NestJS Middleware" [here](https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/blob/feature/express-trpc-req-log-issue-resolved/src/trpc.middleware.ts). `TrpcModule` is defined and imported in `AppModule` after `LoggerModule` so that `LoggerMiddleware` gets executed before `TrpcMiddleware` in request lifecycle. After applying this solution, the following issue has been resolved.

I am putting the source code link here, if it might help someone else having the same issue!
Source code: https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/tree/feature/express-trpc-req-log-issue-resolved

**Comment by akashdevcc** [comment] 2024-04-30 10:13
@iamolegga I used a second approach to resolve this issue, which works in both express and fastify.

Although, this approach required to modify `nestjs-pino` to export the `createLoggerMiddlewares` function (as shown [here](https://github.com/iamolegga/nestjs-pino/compare/master...akashdevcc:nestjs-pino:master)), so that I can use it externally before any middleware in the request lifecycle, as done [here](https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/blob/f624168353cc29dbe52e9209011695aa74c491dc/src/main.ts#L19-L21).

This also requires `autoLogging` set to `false` so that it does not log the `request` logs twice, as the `createLoggerMiddlewares` function now gets executed twice.

I am not sure, if "exporting the `createLoggerMiddlewares` function" in `nestjs-pino` is the ideal approach/solution. But if this change can be implemented with some another ideal approach it will be good to incorporate this. May be passing a `external` flag in the `params` section which bypasses calling `createLoggerMiddlewares` inside `LoggerModule` if it's being used externally.

@iamolegga Waiting for your thoughts on this, I'll be ready to do this work and raise a pull request if you agree.

Here are the source code links:
express: https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/blob/feature/express-trpc-req-log-issue-approach-2
fastify: https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/tree/feature/fastify-trpc-req-log-issue-approach-2
nestjs-pino (forked/modified): https://github.com/akashdevcc/nestjs-pino

**Comment by iamolegga** [comment] 2024-04-30 19:12
Unfortunately, I don't have free time to deep dive into 3rd party experiments with the current module. I'm sure the current module doesn't have to be modified, and internal parts don't need to be exposed to make it work. I believe that trpc or any other framework should first utilize nestjs core principles to make nestjs-related modules work. For example, you provided some specific router, but nestjs already has its own routing system, and the problem should be solved in this layer. Maybe you should write a new trpc adapter first, and then your problem will be solved automatically. I don't know. But what I've seen [here](https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/blob/feature/express-trpc-req-log-issue-resolved/src/trpc.middleware.ts#L25-L31) and [here](https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/blob/feature/express-trpc-req-log-issue-resolved/src/app.router.ts#L14-L19) is surely not how it should be implemented, because you [create a new server](https://github.com/akashdevcc/nestjs-pino-trpc-req-log-issue/blob/feature/express-trpc-req-log-issue-resolved/src/app.router.ts#L13) instead of one used by nestjs itself and see that the async hooks context is lost. I don't want to add support for each exotic solution and support it, nor do I want to expose internals and solve issues when someone uses these internals in his own fashion.

Sorry, but either use your fork or make an idiomatic trpc module for nestjs. Locking.
