### ISSUE TITLE
[BUG] No logs when using a custom express server

### ISSUE THREAD

**Issue by fuglu** [iamolegga/nestjs-pino#534] opened 2021-09-03 11:08 UTC
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**

Only request logs will be written when using a [custom express server](https://docs.nestjs.com/faq/multiple-servers#multiple-simultaneous-servers).
Other `this.logger.log("...")` messages won't show up.

**What is the expected behavior?**

All lines should be logged.

**Please provide minimal example repo. Without it this issue will be closed**

Simple `npx -p @nestjs/cli nest new my-nest-project` example is over here:
https://github.com/fuglu/nestjs-pino-custom-express-server

```bash
# clone and start the service
cd /tmp
git clone https://github.com/fuglu/nestjs-pino-custom-express-server.git
cd nestjs-pino-custom-express-server
npm i
npm start

# and in a second terminal
watch curl localhost:3000
```
The `app.controller.ts` has a ` this.logger.log('Hello Nest');` line which won't show up.

This is the relevant `main.ts`:

```ts
import { NestFactory } from '@nestjs/core';
import {
  ExpressAdapter,
  NestExpressApplication,
} from '@nestjs/platform-express';
import * as express from 'express';
import { Logger } from 'nestjs-pino';
import { AppModule } from './app.module';

// This one works
async function bootstrap() {
  const app = await NestFactory.create(AppModule, { bufferLogs: true });
  app.useLogger(app.get(Logger));
  await app.listen(3000);
}

// This one has only request logs
async function bootstrapCreateServer() {
  const server = express();

  const app = await NestFactory.create<NestExpressApplication>(
    AppModule,
    new ExpressAdapter(server),
    {
      bufferLogs: true,
    },
  );
  app.useLogger(app.get(Logger));

  await app.init();

  server.listen(3000);
}

// bootstrap();
bootstrapCreateServer();

```

**Please mention other relevant information such as Node.js version and Operating System.**

OS: Debian (testing)
Node.js: v16.8.0
Nest: v8.0.6
nestjs-pino: v2.2.0

Thanks for creating nestjs-pino!

**Comment by iamolegga** [comment] 2021-09-03 13:35
Thanks, will check soon. Also, if you know how to fix feel free to open PR

**Comment by iamolegga** [comment] 2021-11-12 21:54
just checked, pretty strange behavior: if comment [this line](https://github.com/fuglu/nestjs-pino-custom-express-server/blob/main/src/main.ts#L25) everything works. So from my point of view, this could be a bug in Nestjs for a specific case when using `Adapter` and `bufferLogs` is set. This can be checked with dummy logger implementation

**Comment by iamolegga** [comment] 2021-11-12 21:58
so as a workaround you can disable logs buffering on startup. Closing but feel free to provide a dummy logger example if you would like to check if this is a bug of nestjs-pino or framework

**Closed by iamolegga** 2021-11-12 21:58 UTC
Labels: bug

**Comment by micalevisk** [comment] 2021-11-12 23:31
@fuglu I think must call `app.listen` instead of `server.listen`. It works if you do that

**Comment by iamolegga** [comment] 2023-07-17 18:25
@128keaton please check if you still see a problem with other loggers (maybe try one [from the docs](https://docs.nestjs.com/techniques/logger#custom-implementation) then this is surely not a bug of the current library. No need to add dirty hacks to handle bugs in the framework.
Otherway feel free to open a bug report with the minimal example here.

**Comment by jeg0330** [comment] 2024-08-16 07:32
The `listen()` function calls `flushLogs()` to clear the logs accumulated in the buffer, but `init()` doesn't call it separately. You can call `flushLogs()` to do so
